---
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - nano
      - sudo
      - htop
      - ca-certificates
      - unzip
    state: present
- name: Set timezone
  community.general.timezone:
    name: Europe/Warsaw
- name: Add user to the sudo group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: sudo
    append: true
- name: Add directory
  ansible.builtin.file:
    path: /appdata
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
- name: Make directory for each app
  ansible.builtin.file:
    path: "/appdata/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"
  loop:
    - jellyfin
    - pihole
    - swingmusic
