services:
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - ${APPDATA_DIR}/vaultwarden/data:/data:Z
