services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
     - ${APPDATA_DIR}/kavita/config:/config
     - ${MEDIA_DIR}/books:/data/books:ro
     - ${MEDIA_DIR}/comics:/data/comics:ro
    ports:
     - "5000:5000"
    restart: always
