services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:2
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - ${APPDATA_DIR}/uptime-kuma/data:/app/data
    environment:
      - TZ=${TZ}
    restart: always
    networks:
     - proxy-nw

networks:
  proxy-nw:
    external: true
