---
- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Tailsacle GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: /etc/apt/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"

- name: Add Tailscale repository to APT
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main"
    state: present
    filename: tailscale

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true

- name: Start Tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true

- name: Make Tailscale usable without root
  ansible.builtin.command:
    cmd: tailscale set --operator={{ ansible_user }}
