services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8099:8080'
    volumes:
      - ${APPDATA_DIR}/stirling-pdf/tessdata:/usr/share/tessdata
      - ${APPDATA_DIR}/stirling-pdf/configs:/configs
      - ${APPDATA_DIR}/stirling-pdf/logs:/logs
      - ${APPDATA_DIR}/stirling-pdf/pipeline:/pipeline
    environment:
      - SECURITY_ENABLELOGIN=false
      - LANGS=pl_PL
    restart: unless-stopped
