services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    dns:
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"
    environment:
      TZ=${TZ}
      WEB_PORT: '8081' 
    volumes:
      - ${APPDATA_DIR}/pihole/etc-pihole:/etc/pihole
      - ${APPDATA_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      - proxy-nw

networks:
  proxy-nw:
    external: true
