services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8085
    volumes:
      - ${APPDATA_DIR}/qbittorrent:/config:Z
      - ${MEDIA_DIR}/downloads:/downloads:z
    ports:
      - "8085:8085"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    dns:
      - 8.8.8.8
