services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    restart: always
    ports:
      - "1970:1970"
    environment:
      - TZ=${TZ}
      # - SWING_PORT=1970
    volumes:
      - ${APPDATA_DIR}/swing-music/data:/data"
      - ${MEDIA_DIR}/music:/music:ro,:Z:"
    networks:
     - proxy-nw

networks:
  proxy-nw:
    external: true
